### ISSUE TITLE
"All Learners" Campaign Count is inaccurate

### ISSUE THREAD

**Issue by bookjunkie93** [curiouslearning/followthelearners#106]
Browser: Chrome Version 83.0.4103.61
OS: OSX Catalina, Local Dev environment
Node Version: v12.6.3
commit: 7f0f24e8bd438a22423b1d12d4d2a93399c0f5f2

**Summary**
When viewing the All Learners tab on the campaigns page, the displayed total count is below the sum of the displayed counts for all donors across all campaigns in the Your Learners page

**Expected Behavior**
The All Learners tab should display a count exactly matching the number of users in the database, which is equal to the sum of the total users reached for each campaign across each donor

**Steps to Reproduce**
1. Checkout commit: 7f0f24e8bd438a22423b1d12d4d2a93399c0f5f2 and run server using `node index.js`
2. In browser, navigate to http://localhost:3000/campaigns
3. Click on the "All Learners" tab
4. Observe the displayed total
5. Click on the "Your Learners" tab
6. Enter email: etondreau@curiouslearning.org
7. Observe total donations for each campaign
8. Refresh page
9. Click on "Your Learners" tab
19. Enter email "gdzavashvili@curiouslearning.org"
20. Observe total donations for each campaign
21. Sum totals for "Your Learners" tab across both e-mails
22. Observe Error.

**Comment by redpixr** [comment]
Added country fields to the users for all donor acquired users values in the DB to make them appear on the All Learners page
