### ISSUE TITLE
Verify learner count

### ISSUE THREAD

**Issue by burrage** [curiouslearning/followthelearners#110]
**User Story**
As a developer,
I want to run a BigQuery query to verify that the # of learners that I am seeing in All Learners matches what is displayed in the FTL app,
So that we can 1.) check our work to verify ingestion is working as intended and 2.) that we get a sense of how many people download the app and actually become Learner Level 1 by opening the app.

**Acceptance Criteria**
Given that I am viewing the All Learners tab of the FtL web app and the BigQuery Console for Follow the Learners
when I run the following query in BigQuery, I should see a number equal to the number of learners listed on the All Learners tab.

**Query:**

```
SELECT 
  COUNT(event_name) 
FROM 
  `ftm-hindi.analytics_174638281.events_*`
WHERE 
  event_name = "first_open" AND traffic_source.name = "India-Hindi-FTM-5_11_20_Campaign"
UNION ALL
SELECT 
  COUNT(event_name) 
FROM 
  `ftm-swahili.analytics_160694316.events*`
WHERE 
  event_name = "first_open" AND traffic_source.name = "Tanzania-Swahili-FTM-5_11_20_Campaign"
```

**Comment by bookjunkie93** [comment]
Currently the query returns the following information:
India Campaign: 187 learners
Tanzania Campaign: 248 learners
