### ISSUE TITLE
Automatically choose street view based on region

### ISSUE THREAD

**Issue by burrage** [curiouslearning/followthelearners#121]
**User Story**
As a Product Owner,
I want to programmatically display a street view for a given region,
So that we don't have to manually find a street view link for every city and that assigning street views is more scalable.

**Acceptance Criteria**
Given that we have appropriate loc_ref information in the DB for a new country,
When I view the "All Learners" tab and navigate to that particular country's region view and click on any of the visible region pins,
Then I should get a Google streetview that is within the bounds of that particular region of the country.

**Comment by redpixr** [comment]
Adding more research details!
