### ISSUE TITLE
Campaigns Don't Scroll Horizontally on Desktop

### ISSUE THREAD

**Issue by bookjunkie93** [curiouslearning/followthelearners#237]
When loading the `/campaigns` page of the project on a computer, all campaigns are fit to the width of the page, instead of organized in a horizontal scrollbar approximately 4 campaign objects wide. This is causing a readability issue with the campaigns page when there is a large number of active campaigns

**Acceptance Criteria:**
Given that I am loading followthelearners.curiouslearning.org/campaigns on a computer, and there are more than 4 active campaigns

I should see a maximum of 4 campaigns visible on the screen, and a horizontal scroll bar that hides the rest of the campaigns to the right

**Comment by burrage** [comment]
Addressed in #273
