### ISSUE TITLE
Standardize India and Tanzania streetview "locations" array to geopoint data type

### ISSUE THREAD

**Issue by burrage** [curiouslearning/followthelearners#267]
There are older India and Tanzania streetviews in the "locations" array that are a map + two numbers. We should change those maps + two numbers to a geopoint instead to simplify the DB and expand the functionality we would have using a geopoint.

**Comment by redpixr** [comment]
We should probably write a function that gets all that region data and then creates GeoPoint values as street view locations and then save everything
