### ISSUE TITLE
QA development

### ISSUE THREAD

**Issue by burrage** [curiouslearning/followthelearners#372]
@bookjunkie93 can you put together a QA plan for George and I for what to test in the development branch and how we should test it across end of Sprint #14/start of #15 exactly please?

**Comment by bookjunkie93** [comment]
QA Notes & Stories for Auth pipeline
====
Initialize environment
----
- check out the `develop` branch and run `npm install` in the project root and in `/functions` to ensure all packages are installed.
- use a text editor to comment out line 8 and un-comment line 33 in `/views/donate.pug`
-use (Unix `netstat -aon|grep "[port_num]"`||Windows: `netstat-aon|findStr "[port_num]"`) to ensure ports are free for the Firebase emulators. (ports to check: [8080, 4000, 5000]). If any tasks are occupying those ports, use (Unix: `kill [PID]` || Windows: `taskkill /F /PID [PID]` where [PID] is the id number of the listening task) to free up the ports for use by the Firebase Emulators. 
- Initialize the test database and local server and navigate to [localhost:3000/campaigns](http://localhost3000:/campaigns)

New Donation
----
User Flow:
- choose any active campaign and go to the donate page
- on the test donate page, fill out the form using an e-mail you have access to (i.e: personal, CL e-mail, dummy email, etc.) and give an amount >=5.00. in the campaign field, enter `(direct)|[region]` where `[region]` is any country, continent, or the word 'any'.
- Click Submit and check the terminal instance running firebase emulators for error messages
- Check the email you used to submit the donation for your confirmation email
- Once you have found the confirmation email, click the link to open a new browser window with the local server
- Type the same email used to make the donation into the alert box and confirm that the Your Learners tab successfully loads.
- Confirm that the number of learners assigned to you is <= `(donation amount/)/7`
  -  The current cost/learner globally is 0.25

Database Checks:
- Once the donation has been completed, check the [FTL Firebase Auth Console](https://console.firebase.google.com/u/0/project/follow-the-learners/authentication/users) to confirm that your email has been registered as a donor. Copy the uid assigned to your email (You can and should safely delete this user once testing has been finished)
- Check the Firebase Emulator Suite for a donation document existing at `/donor_master/{uid}`
- Confirm the `learnerCount` field is equal to the number of learners displayed on the Your Learners Tab
- copy the donation document's `donationID` field value
- navigate to `user_pool/` and use the emulator's filter tool to create the following filter: `('user_pool').where('sourceDonation', '==', {donationID})`
- Apply the filter and confirm the existence of learners in the pool 
- Check some users to confirm the `sourceDonor` field is equal to the Firebase auth uid created for your email
- Check some users to confirm their `userStatus` field is set to 'assigned', and they have an `assignedOn` field with a timestamp value equivalent to the time of your donation
- Check some users to confirm their `dateCreated` field has a timestamp value no older than 1 week from the date of donation
