### ISSUE TITLE
Create data flow document

### ISSUE THREAD

**Issue by burrage** [curiouslearning/followthelearners#4]
**User Story**
As a developer,
I want to take my preliminary database schema and map out from what existing locations can I pull or push the data needed for each table in the database,
So that I can identify where we can expect each piece of data to come from and make sure we have access to that particular data.

**Comment by bookjunkie93** [comment]
Document for review: https://www.lucidchart.com/invitations/accept/18bf138d-4037-4ebb-84f3-b98b8f8a141a
