### ISSUE TITLE
Unit tests and logging for automated backend processes

### ISSUE THREAD

**Issue by burrage** [curiouslearning/followthelearners#401]
**User Story**
As a developer,
I want to be able to write unit tests for all the major backend processes and subcomponents of those processes (data ingestion, donation storing, and initial and subsequent learner assignment) and log the results of those tests,
So that it is easy to test these critical functions when code changes.

**Acceptance Criteria**
@bookjunkie93 -- would you mind listing out all the tests here that you are going to write and how to execute those tests? Thanks.

**Comment by srivatsansraghavan** [comment]
Hi,

Is this repo open for outsiders to contribute?

If yes, I did all that is mentioned in the readme, but I guess I need to get keys to proceed further.

**Comment by burrage** [comment]
@srivatsansraghavan Hello! Thanks for your interest in contributing to the project. At this particular moment, we are not accepting outside contributions as we get to a stable v1 of the system but we may very well in the future!

What types of projects are you looking to contribute to and I assume you are most interested in writing QA tests?

Also feel free to shoot me an e-mail at bburrage@curiouslearning.org if you would like to chat further.
