### ISSUE TITLE
Move "Give Now" button on top of the campaign image

### ISSUE THREAD

**Issue by redpixr** [curiouslearning/followthelearners#81]
As a User, I want to see "Give Now" button for each campaign on the campaigns page to always be displayed above the fold, so that it's easier to access the donation page without having to scroll down on devices with certain screen sizes. 

Acceptance Criteria
Given that I am on the FtL landing page
When I look at the campaign cards, I should see the "Give Now" button displayed without scrolling
And, when I scroll down, the "Give Now" button should "float" until it reaches the bottom of the campaign card
And, when I scroll up so that the bottom of the campaign card is below the fold, the "Give Now" button should once again "float"

**Comment by bookjunkie93** [comment]
Updated the User Story and Acceptance Criteria to use a more dynamic "floating" design for the give now buttons on campaigns
